[package]
name = "pokemon-api"
version = "0.1.0"
authors = ["Matthew Palmer <mspalmer91@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.17"
serde_json = "1.0.39"
serde = { version = "1.0.91", features = ["derive"] }
