[package]
name = "accounting"
version = "0.1.0"
authors = ["Matthew Palmer <matt@silvercreekit.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.15"
serde_json = "1.0.39"
serde = { version = "1.0.90", features = ["derive"] }
