[package]
name = "pokeapi"
version = "0.0.1"
authors = ["Matthew Palmer <mspalmer91@gmail.com>"]
edition = "2018"

[lib]
name = "pokeapi"
path = "src/lib.rs"

[dependencies]
reqwest = "0.9.17"
serde_json = "1.0.39"
serde = { version = "1.0.91", features = ["derive"] }
